---
title: Jasper B. Hammer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@jasperbhammer.com
description: Get the latest news from author Jasper B. Hammer.
baseurl: ''
url: ''
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
